# Flight delay prediction

--> Analyzing data and handling missing values.
--> Getting delay of flight

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import norm

In [ ]:
fin_train=pd.read_csv('merged_2004onindex.csv')

In [55]:
fin_train.head()

Unnamed: 0   FlightNumber  Year  Month  DayofMonth  DayOfWeek  \
0           0  BOS_CLE_29089  2004      9          20          1   
1           1  CLE_ATL_44346  2004     11          19          5   
2           2  SNA_LAS_44378  2004      5           4          2   
3           3  CLT_TPA_51502  2004      7           6          2   
4           4  MSP_ORD_44884  2004      9          23          4   

   ScheduledDepTime  ScheduledArrTime  ScheduledTravelTime Origin  ...  Time  \
0              1000              1154                  114    BOS  ...  1350   
1              1440              1634                  114    CLE  ...  1910   
2              1800              1902                   62    SNA  ...  2010   
3              1400              1533                   93    CLT  ...  1010   
4               830               946                   76    MSP  ...  1050   

          SkyConditions Visibility   DBT  RelativeHumidityPercent WindSpeed  \
0         FEW075 BKN090       10SM  32.0                     40.0      15.0   
1         BKN028 OVC033       10SM  21.0                     74.0       5.0   
2         FEW025 OVC032        9SM  25.0                     75.0       4.0   
3  SCT015 BKN020 OVC028        4SM  25.0                     92.0       0.0   
4         BKN013 OVC021     1.75SM  27.0                     85.0       0.0   

   WindDirection  WindGustValue  StationPressure  HourlyPrecip  
0            160            0.0            30.05           0.0  
1            VRB            0.0            30.06           0.0  
2            VRB            0.0            30.06           0.0  
3            000            0.0            29.98           0.0  
4            000            0.0            29.99           0.0  

[5 rows x 34 columns]

In [56]:
fin_train.shape

(7861, 34)

In [57]:
fin_train.isnull().sum()

Unnamed: 0                  0
FlightNumber                0
Year                        0
Month                       0
DayofMonth                  0
DayOfWeek                   0
ScheduledDepTime            0
ScheduledArrTime            0
ScheduledTravelTime         0
Origin                      0
Destination                 0
Distance                    0
ActualArrivalTimeStamp      0
YearMonthDay_x              0
WeatherStationID            0
AirportID                   0
GroundHeight                0
StationHeight               0
BarometerHeight             0
Latitude                    0
Longitude                   0
TimeZone                    0
Unnamed: 0.1                0
YearMonthDay_y              0
Time                        0
SkyConditions               9
Visibility                 73
DBT                        47
RelativeHumidityPercent    47
WindSpeed                   3
WindDirection               3
WindGustValue               3
StationPressure             0
HourlyPrec

In [58]:
print('Number of total missing values:', fin_train.isna().sum().sum())
print('df1 shape:', fin_train.shape)

Number of total missing values: 198
df1 shape: (7861, 34)


In [59]:
fin_train.SkyConditions.unique()               

array(['FEW075 BKN090', 'BKN028 OVC033', 'FEW025 OVC032',
       'SCT015 BKN020 OVC028', 'BKN013 OVC021', 'OVC011', 'SCT021 OVC030',
       'FEW017 OVC028', 'OVC006', 'FEW045 BKN060 OVC080', 'BKN010 OVC017',
       'OVC009', 'BKN016 OVC023', 'OVC004', 'SCT003 BKN007 OVC017',
       'BKN002 OVC008', 'BKN006 BKN010 OVC015', 'BKN010 OVC018',
       'FEW027 BKN032 OVC041', 'SCT021 BKN027 OVC039', 'BKN005 OVC010',
       'FEW009 BKN015 OVC023', 'SCT021 BKN029 OVC043',
       'BKN011 BKN022 OVC029', 'FEW006 SCT019 BKN031',
       'FEW018 BKN029 OVC080', 'FEW013 SCT024 BKN038',
       'BKN005 BKN011 OVC024', 'BKN008 OVC014', 'FEW007 BKN013 OVC028',
       'SCT007 BKN011 OVC019', 'FEW010 OVC016', 'OVC014',
       'FEW006 SCT010 BKN014', 'BKN006 BKN044 OVC050', 'BKN013 OVC018',
       'OVC010', 'OVC016', 'FEW009 SCT048 BKN065', 'BKN001 OVC040',
       'BKN002 OVC036', 'BKN001', 'BKN007 OVC018', 'FEW006 BKN024 OVC030',
       'SCT029 BKN047', 'BKN026 OVC037', 'BKN006 BKN016 OVC055', 'CLR',
     

In [60]:
fin_train.Visibility.unique()               

array(['10SM', '9SM', '4SM', '1.75SM', '1.25SM', '7SM', '1.5SM', '2.5SM',
       '0.5SM', nan, '1SM', '3SM', '0.75SM', '6SM', '8SM', '2SM', '5SM',
       '0.25SM'], dtype=object)

In [61]:
fin_train.DBT.unique()               

array([32., 21., 25., 27., 28., nan, 34., 23., 12., 14., 16., 30., 19.,
       18., 10., 46., 36., 39., 41., 64., 37., 45., 43., 48., 52., 54.,
       55., 57., 50., 59., 61., 63., 66., 68.,  7.,  9.,  1.,  3., -6.,
        0., -4.,  5., -2., -8., 70., 72., 73., 75., 77., 79., 81., 82.,
       47., 56., 58., 22., 38., 20., 26., 35., 62., 65., 60., 49., 44.,
       40., 24., 33., 29., 31., 42., 67., 53., 71., 69., 51., 84., 80.,
       76., 78., 83., 74., 86.])

In [62]:
fin_train.DBT.nunique()               

82

In [63]:
fin_train.RelativeHumidityPercent.unique()

array([ 40.,  74.,  75.,  92.,  85.,  96.,  89.,  nan,  54., 100.,  62.,
        67.,  84.,  88.,  69.,  82.,  72.,  77.,  73.,  53.,  81.,  34.,
        65.,  76.,  19.,  70.,  50.,  37.,  32.,  30.,  33.,  28.,  25.,
        27.,  49.,  58.,  56.,  79.,  42.,  38.,  35.,  31.,  29.,  26.,
        24.,  23.,  22.,  21.,  43.,  48.,  41.,  20.,  18.,  51.,  61.,
        47.,  45.,  46.,  52.,  36.,  15.,  17.,  14.,  16.,  39.,  13.,
        12.,  11.,  57.,  55.,  44.,  63.,  71.,  60.,  68.,  83.,  80.,
        91.,  64.,  66.,  10.,  59.,  78.,  86.,  93.,  87.,   9.,   8.,
         7.,   6.,   5.,   4.,   3.,  97.])

In [64]:
fin_train.WindSpeed.unique()

array([15.,  5.,  4.,  0.,  6., 16.,  8., 11., 12., 14.,  7., 17.,  9.,
        3., 13., 10., nan, 18., 20., 21., 19., 24., 23., 22., 27., 28.,
       30., 25., 26., 33., 29.])

In [65]:
fin_train.WindDirection.unique() 

array(['160', 'VRB', '000', '280', '240', '290', '300', '220', '230',
       '210', '270', '250', '150', '130', '260', '310', '100', '110',
       '090', '200', '120', nan, '080', '140', '320', '180', '330', '190',
       '170', '050', '070', '010', '060', '020', '030', '350', '040',
       '340', '360'], dtype=object)

In [66]:
fin_train.WindGustValue.unique() 

array([ 0., 27., 24., 21., 19., 22., 25., 23., 17., nan, 15., 26., 28.,
       29., 31., 30., 18., 20., 16., 32., 14., 33., 35., 36., 37., 34.,
       38., 40., 42., 39., 41.])

In [67]:
fin_train.HourlyPrecip.unique() 

array([0.  , 0.02, 0.1 ,  nan, 0.01, 0.03, 0.06, 0.07, 0.09, 0.04])

In [68]:
fin_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7861 entries, 0 to 7860
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Unnamed: 0               7861 non-null   int64  
 1   FlightNumber             7861 non-null   object 
 2   Year                     7861 non-null   int64  
 3   Month                    7861 non-null   int64  
 4   DayofMonth               7861 non-null   int64  
 5   DayOfWeek                7861 non-null   int64  
 6   ScheduledDepTime         7861 non-null   int64  
 7   ScheduledArrTime         7861 non-null   int64  
 8   ScheduledTravelTime      7861 non-null   int64  
 9   Origin                   7861 non-null   object 
 10  Destination              7861 non-null   object 
 11  Distance                 7861 non-null   int64  
 12  ActualArrivalTimeStamp   7861 non-null   object 
 13  YearMonthDay_x           7861 non-null   object 
 14  WeatherStationID        

### Treating null values
Categorical dtypes are replaced with median and mode

Numericcal dtypes are replaced with mean

Windspeed null values is replaced with forward fill

In [69]:
# Calculate the proportion of missing data

def checkMissing(data,perc=0):
    """ 
    Takes in a dataframe and returns
    the percentage of missing value.
    """
    missing = [(i, data[i].isna().mean()*100) for i in data]
    missing = pd.DataFrame(missing, columns=["column_name", "percentage"])
    missing = missing[missing.percentage > perc]
    print(missing.sort_values("percentage", ascending=False).reset_index(drop=True))

print("Proportion of missing data in columns")
checkMissing(fin_train)

Proportion of missing data in columns
               column_name  percentage
0               Visibility    0.928635
1                      DBT    0.597888
2  RelativeHumidityPercent    0.597888
3             HourlyPrecip    0.165373
4            SkyConditions    0.114489
5                WindSpeed    0.038163
6            WindDirection    0.038163
7            WindGustValue    0.038163


In [75]:
fin_train.columns

Index(['Unnamed: 0', 'FlightNumber', 'Year', 'Month', 'DayofMonth',
       'DayOfWeek', 'ScheduledDepTime', 'ScheduledArrTime',
       'ScheduledTravelTime', 'Origin', 'Destination', 'Distance',
       'ActualArrivalTimeStamp', 'YearMonthDay_x', 'WeatherStationID',
       'AirportID', 'GroundHeight', 'StationHeight', 'BarometerHeight',
       'Latitude', 'Longitude', 'TimeZone', 'Unnamed: 0.1', 'YearMonthDay_y',
       'Time', 'SkyConditions', 'Visibility', 'DBT', 'RelativeHumidityPercent',
       'WindSpeed', 'WindDirection', 'WindGustValue', 'StationPressure',
       'HourlyPrecip'],
      dtype='object')

In [76]:
fin_train.fillna({"Visibility":fin_train['Visibility'].mode()[0], "DBT": fin_train['DBT'].median(), 
"RelativeHumidityPercent": fin_train['RelativeHumidityPercent'].mean(),
                  "HourlyPrecip": fin_train['HourlyPrecip'].median(),
          "SkyConditions":fin_train['SkyConditions'].mode()[0],
          "WindSpeed": fin_train['WindSpeed'].median(),
           "WindGustValue":fin_train['WindGustValue'].mode()[0],
          },inplace=True)

In [77]:
fin_train.isnull().sum()

Unnamed: 0                 0
FlightNumber               0
Year                       0
Month                      0
DayofMonth                 0
DayOfWeek                  0
ScheduledDepTime           0
ScheduledArrTime           0
ScheduledTravelTime        0
Origin                     0
Destination                0
Distance                   0
ActualArrivalTimeStamp     0
YearMonthDay_x             0
WeatherStationID           0
AirportID                  0
GroundHeight               0
StationHeight              0
BarometerHeight            0
Latitude                   0
Longitude                  0
TimeZone                   0
Unnamed: 0.1               0
YearMonthDay_y             0
Time                       0
SkyConditions              0
Visibility                 0
DBT                        0
RelativeHumidityPercent    0
WindSpeed                  0
WindDirection              3
WindGustValue              0
StationPressure            0
HourlyPrecip               0
dtype: int64

In [78]:
col_name = "WindDirection"

# find the index no
index_no = fin_train.columns.get_loc(col_name)

print("Index of {} column in given dataframe is : {}".format(col_name, index_no))


Index of WindDirection column in given dataframe is : 30


In [79]:
fin_train.WindDirection=fin_train.WindDirection.ffill()

In [80]:
fin_train.isnull().sum()

Unnamed: 0                 0
FlightNumber               0
Year                       0
Month                      0
DayofMonth                 0
DayOfWeek                  0
ScheduledDepTime           0
ScheduledArrTime           0
ScheduledTravelTime        0
Origin                     0
Destination                0
Distance                   0
ActualArrivalTimeStamp     0
YearMonthDay_x             0
WeatherStationID           0
AirportID                  0
GroundHeight               0
StationHeight              0
BarometerHeight            0
Latitude                   0
Longitude                  0
TimeZone                   0
Unnamed: 0.1               0
YearMonthDay_y             0
Time                       0
SkyConditions              0
Visibility                 0
DBT                        0
RelativeHumidityPercent    0
WindSpeed                  0
WindDirection              0
WindGustValue              0
StationPressure            0
HourlyPrecip               0
dtype: int64

In [81]:
fin_train=fin_train.drop(['Unnamed: 0','Unnamed: 0.1'],axis=1)

In [82]:
fin_train.WindDirection

0       160
1       VRB
2       VRB
3       000
4       000
       ... 
7856    220
7857    270
7858    280
7859    340
7860    330
Name: WindDirection, Length: 7861, dtype: object

In [83]:
print(fin_train['WindDirection'].value_counts()['VRB'])

323


In [84]:
print(fin_train['WindDirection'].mode())

0    000
dtype: object


In [85]:
fin_train.loc[fin_train["WindDirection"] == "VRB", "WindDirection"] = 000

In [86]:
fin_train.WindDirection.unique()

array(['160', 0, '000', '280', '240', '290', '300', '220', '230', '210',
       '270', '250', '150', '130', '260', '310', '100', '110', '090',
       '200', '120', '080', '140', '320', '180', '330', '190', '170',
       '050', '070', '010', '060', '020', '030', '350', '040', '340',
       '360'], dtype=object)

In [87]:
fin_train.isnull().sum()

FlightNumber               0
Year                       0
Month                      0
DayofMonth                 0
DayOfWeek                  0
ScheduledDepTime           0
ScheduledArrTime           0
ScheduledTravelTime        0
Origin                     0
Destination                0
Distance                   0
ActualArrivalTimeStamp     0
YearMonthDay_x             0
WeatherStationID           0
AirportID                  0
GroundHeight               0
StationHeight              0
BarometerHeight            0
Latitude                   0
Longitude                  0
TimeZone                   0
YearMonthDay_y             0
Time                       0
SkyConditions              0
Visibility                 0
DBT                        0
RelativeHumidityPercent    0
WindSpeed                  0
WindDirection              0
WindGustValue              0
StationPressure            0
HourlyPrecip               0
dtype: int64

### Getting arrival delay

In [88]:
fin_train.YearMonthDay_x

0       2004-09-20
1       2004-11-19
2       2004-05-04
3       2004-07-06
4       2004-09-23
           ...    
7856    2004-05-27
7857    2004-11-29
7858    2004-05-11
7859    2004-01-04
7860    2004-11-06
Name: YearMonthDay_x, Length: 7861, dtype: object

In [89]:
fin_train.YearMonthDay_y

0       2004-01-01
1       2004-01-01
2       2004-01-01
3       2004-01-02
4       2004-01-02
           ...    
7856    2004-03-28
7857    2004-03-28
7858    2004-03-28
7859    2004-03-28
7860    2004-03-28
Name: YearMonthDay_y, Length: 7861, dtype: object

In [90]:
fin_train['YearMonthDay_x'].equals(fin_train['YearMonthDay_y'])

False

In [91]:
fin_train['ScheduledArrTime'] = fin_train['ScheduledArrTime'].astype('str')

In [92]:
fin_train['scheduled_arr_d_t']= fin_train["YearMonthDay_x"].astype(str) +" "+ fin_train["ScheduledArrTime"]

In [93]:
fin_train.columns

Index(['FlightNumber', 'Year', 'Month', 'DayofMonth', 'DayOfWeek',
       'ScheduledDepTime', 'ScheduledArrTime', 'ScheduledTravelTime', 'Origin',
       'Destination', 'Distance', 'ActualArrivalTimeStamp', 'YearMonthDay_x',
       'WeatherStationID', 'AirportID', 'GroundHeight', 'StationHeight',
       'BarometerHeight', 'Latitude', 'Longitude', 'TimeZone',
       'YearMonthDay_y', 'Time', 'SkyConditions', 'Visibility', 'DBT',
       'RelativeHumidityPercent', 'WindSpeed', 'WindDirection',
       'WindGustValue', 'StationPressure', 'HourlyPrecip',
       'scheduled_arr_d_t'],
      dtype='object')

In [94]:
fin_train.ActualArrivalTimeStamp

0       20-09-2004 11:54
1       19-11-2004 18:55
2       04-05-2004 19:02
3       06-07-2004 15:33
4       23-09-2004 09:46
              ...       
7856    27-05-2004 09:00
7857    29-11-2004 13:54
7858    11-05-2004 14:05
7859    04-01-2004 12:14
7860    06-11-2004 17:56
Name: ActualArrivalTimeStamp, Length: 7861, dtype: object

In [95]:
fin_train.scheduled_arr_d_t

0       2004-09-20 1154
1       2004-11-19 1634
2       2004-05-04 1902
3       2004-07-06 1533
4        2004-09-23 946
             ...       
7856     2004-05-27 900
7857    2004-11-29 1354
7858    2004-05-11 1405
7859    2004-01-04 1214
7860    2004-11-06 1613
Name: scheduled_arr_d_t, Length: 7861, dtype: object

In [96]:
fin_train['ActualArrivalTimeStamp'] = pd.to_datetime(fin_train['ActualArrivalTimeStamp'], format="%d-%m-%Y %H:%M")


In [97]:
fin_train.ActualArrivalTimeStamp

0      2004-09-20 11:54:00
1      2004-11-19 18:55:00
2      2004-05-04 19:02:00
3      2004-07-06 15:33:00
4      2004-09-23 09:46:00
               ...        
7856   2004-05-27 09:00:00
7857   2004-11-29 13:54:00
7858   2004-05-11 14:05:00
7859   2004-01-04 12:14:00
7860   2004-11-06 17:56:00
Name: ActualArrivalTimeStamp, Length: 7861, dtype: datetime64[ns]

In [98]:
fin_train['scheduled_arr_d_t'] = pd.to_datetime(fin_train['scheduled_arr_d_t'], format="%Y-%m-%d %H%M")


In [99]:
fin_train.scheduled_arr_d_t

0      2004-09-20 11:54:00
1      2004-11-19 16:34:00
2      2004-05-04 19:02:00
3      2004-07-06 15:33:00
4      2004-09-23 09:46:00
               ...        
7856   2004-05-27 09:00:00
7857   2004-11-29 13:54:00
7858   2004-05-11 14:05:00
7859   2004-01-04 12:14:00
7860   2004-11-06 16:13:00
Name: scheduled_arr_d_t, Length: 7861, dtype: datetime64[ns]

In [100]:
merged_df=fin_train

In [101]:
merged_df['Arrdelay'] = (merged_df.ActualArrivalTimeStamp - merged_df.scheduled_arr_d_t) / pd.Timedelta(minutes=1)

In [102]:
merged_df.Arrdelay.nunique()

155

In [103]:
merged_df.head(20)

FlightNumber  Year  Month  DayofMonth  DayOfWeek  ScheduledDepTime  \
0   BOS_CLE_29089  2004      9          20          1              1000   
1   CLE_ATL_44346  2004     11          19          5              1440   
2   SNA_LAS_44378  2004      5           4          2              1800   
3   CLT_TPA_51502  2004      7           6          2              1400   
4   MSP_ORD_44884  2004      9          23          4               830   
5   CVG_GRR_45655  2004      9          26          7              1730   
6   DFW_STL_53369  2004      5           5          3              1330   
7   ACV_SFO_50785  2004      9          15          3               655   
8   BHM_DFW_34260  2004      5          28          5              1425   
9   DFW_PIT_33678  2004      9          11          6               847   
10  GNV_ATL_31276  2004      7          18          7              1520   
11  DFW_SJU_32640  2004      3          24          3              1521   
12  GJT_SLC_30446  2004      1           3          6              1143   
13  IAD_DAY_32236  2004      5          21          5               915   
14  SNA_DFW_49976  2004      5          18          2               815   
15  IAH_MEM_41435  2004     11          16          2              1535   
16  ATL_JAX_34808  2004      3          18          4              1438   
17  LGB_JFK_40880  2004      9          25          6               900   
18  RDU_LGA_31104  2004      7           2          5              1430   
19  MDW_CLT_45044  2004      3          21          7               825   

   ScheduledArrTime  ScheduledTravelTime Origin Destination  ...  Visibility  \
0              1154                  114    BOS         CLE  ...        10SM   
1              1634                  114    CLE         ATL  ...        10SM   
2              1902                   62    SNA         LAS  ...         9SM   
3              1533                   93    CLT         TPA  ...         4SM   
4               946                   76    MSP         ORD  ...      1.75SM   
5              1832                   62    CVG         GRR  ...      1.25SM   
6              1517                  107    DFW         STL  ...         7SM   
7               758                   63    ACV         SFO  ...        10SM   
8              1625                  120    BHM         DFW  ...       1.5SM   
9              1223                  156    DFW         PIT  ...        10SM   
10             1658                   98    GNV         ATL  ...      1.75SM   
11             2143                  262    DFW         SJU  ...       1.5SM   
12             1248                   65    GJT         SLC  ...       2.5SM   
13             1106                  111    IAD         DAY  ...       0.5SM   
14             1310                  175    SNA         DFW  ...      1.25SM   
15             1709                   94    IAH         MEM  ...        10SM   
16             1546                   68    ATL         JAX  ...       1.5SM   
17             1720                  320    LGB         JFK  ...         1SM   
18             1555                   85    RDU         LGA  ...       0.5SM   
19             1110                  105    MDW         CLT  ...       2.5SM   

     DBT RelativeHumidityPercent  WindSpeed WindDirection  WindGustValue  \
0   32.0               40.000000       15.0           160            0.0   
1   21.0               74.000000        5.0             0            0.0   
2   25.0               75.000000        4.0             0            0.0   
3   25.0               92.000000        0.0           000            0.0   
4   27.0               85.000000        0.0           000            0.0   
5   28.0               96.000000        0.0           000            0.0   
6   28.0               89.000000        0.0           000            0.0   
7   28.0               96.000000        5.0             0            0.0   
8   46.0               43.526619        6.0           280       

In [104]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7861 entries, 0 to 7860
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype         
---  ------                   --------------  -----         
 0   FlightNumber             7861 non-null   object        
 1   Year                     7861 non-null   int64         
 2   Month                    7861 non-null   int64         
 3   DayofMonth               7861 non-null   int64         
 4   DayOfWeek                7861 non-null   int64         
 5   ScheduledDepTime         7861 non-null   int64         
 6   ScheduledArrTime         7861 non-null   object        
 7   ScheduledTravelTime      7861 non-null   int64         
 8   Origin                   7861 non-null   object        
 9   Destination              7861 non-null   object        
 10  Distance                 7861 non-null   int64         
 11  ActualArrivalTimeStamp   7861 non-null   datetime64[ns]
 12  YearMonthDay_x           7861 non-

### Train data has been treated with null values and arrived at delay column.
##### Downloading the data frame for further process.

In [105]:
merged_df.to_csv('final1_train.csv')

In [107]:
merged_df.shape

(7861, 34)